{{- if and .Values.global (not .Values.global.namespace) }}
kind: Namespace
apiVersion: {{ include "apiVersion" . }}
metadata:
  name: {{ include "iperf3.fullname" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ include "iperf3.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- end}}

{{- if not .Values.global }}
kind: Namespace
apiVersion: {{ include "apiVersion" . }}
metadata:
  name: {{ include "iperf3.fullname" . }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4}}
{{- end }}
  labels:
    app: {{ include "iperf3.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
{{- end }}
{{- end }}